services:
  db:
    image: postgres:alpine
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  smtp-server:
    build:
      context: .
      dockerfile: smtp-server/Dockerfile
    env_file:
      - .env.docker
    ports:
      - "2525:2525"
    depends_on:
      - db
    volumes:
      - ./cert.pem:/cert.pem
      - ./key.pem:/key.pem
      - ./cert:/cert

volumes:
  postgres-db: